Add crocodiles functional tests
Aleksandra-Milenkovic/Java_Template pull request #8
Opened 2021-10-29 14:37 UTC by Aleksandra-Milenkovic

2021-11-03 15:12 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/calls/CrocodilesAPI.java
> +    public static CreateCrocodileResponse getCreatedCrocodile(String accessToken, Integer id) {
Koja je razlika izmedju ove dve metode getMyCrocodile i getCreatedCrocodile?

2021-11-03 15:16 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/calls/CrocodilesAPI.java
> +    public static CreateCrocodileResponse getCreatedCrocodile(String accessToken, Integer id) {
Vidim da je sve isto sem sto jednom vracas CrocodileResponse a drugi put CreateCrocodileResponse koji extenduje CrocodileResponse

2021-11-03 15:19 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/common/GsonFunctions.java
> +       String json = jsonResponse.toString();
Sto si ovo menjala?

2021-11-03 15:19 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/constants/DataProviderNames.java
> +    public static final String VERIFY_DELETED_CROCODILE= "" +
Zasto si ovo ovako napisala? :D

2021-11-03 15:22 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/data/model/common/crocodiles/CrocodilesResponse.java
> +public abstract class CrocodilesResponse extends ErrResponse implements Serializable{
A sto mora da bude abstraktna klasa?

2021-11-03 15:26 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/data/model/crocodiles/EmptyCrocodileResponse.java
> +public class EmptyCrocodileResponse extends ErrResponse implements Serializable {
Ovo brisemo

2021-11-03 15:30 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/data/provider/crocodile/CrocodileProvider.java
>  package com.example.test.api.data.provider.crocodile;
Nemamo potrebu da svaki put koristimo CrocodileProvider ovako, vidis da si ovde za svaki endpoint imala po jedan test case tako da nema potrebe da to prebacujemo ovde u provider ovu pripremu podataka. To radimo kada imamo vise casea, recimo ovde da si napravila da testiras sa vise razlicitih user onda bi imalo smisla

2021-11-03 15:32 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/data/provider/crocodile/CrocodileProvider.java
Sto ovaj token koji svuda saljes ne izvuces ovde i da ga samo prosledis, nema potrebe da zovemo 4, 5 puta isti poziv :)

2021-11-03 15:37 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/asserts/CrocodileAssert.java
> +        if (CrocodilesAPI.getCreatedCrocodile(accessToken, actualCrocodileResponse.getId()).equals(null)) {
Ovde pi pozvala onu metodu getMyCrocodile, jer cemo ovu da obrisemo

2021-11-03 15:40 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        UpdateCrocodileResponse actualUpdatedCrocodileResponse= CrocodilesAPI.updateCrocodile(accessToken,updateCrocodileRequest,1);
Od kad harcodiramo id-eve?

2021-11-03 15:40 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        UpdateCrocodileResponse actualUpdatedCrocodileResponse= CrocodilesAPI.updateCrocodile(accessToken,updateCrocodileRequest,1);
I svuda na dole, fali nam priprema podataka ;)

2021-11-03 15:41 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        UpdateCrocodileResponse actualUpdatedCrocodileResponse= CrocodilesAPI.updateCrocodile(accessToken,updateCrocodileRequest,1);
Ona metoda nadji mi createCrocodileIfNoneExist metoda da se napravi i da se iskoristi svuda.

2021-11-03 15:58 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/data/model/crocodiles/PatchCrocodileResponse.java
> +    public void parseResponse(PatchCrocodileRequest patchCrocodileRequest) {
Ajde da probamo da napravimo patch ovde kako treba, napravices tri razlicita requesta za updatovanje svakog field-a posebno pa cemo u odnosu na to da radimo parseResponse kako treba sa id-em i ostalim podacima koji se ne menjaju,

2021-11-04 12:18 UTC, Aleksandra-Milenkovic commented on src/test/java/com/example/test/api/calls/CrocodilesAPI.java
> +    public static CreateCrocodileResponse getCreatedCrocodile(String accessToken, Integer id) {
Pa da, getMyCrocodile koristim kad mi je potreban samo taj krokodil koji ima klasican response, a getCreatedCrocodile koristim kad mi je potreban response koji u sebi ima parse metodu. E sad, ja mogu za to da koristim jednu istu klasu, zapravo mogu vise parse metoda i za create, i za update i za patch da dodam u CrocodilesResponse i samo njega da koristim. Dvoumila sam se tu.

2021-11-04 12:23 UTC, Aleksandra-Milenkovic commented on src/test/java/com/example/test/api/calls/CrocodilesAPI.java
> +    public static EmptyCrocodileResponse deleteCrocodile(String accessToken, Integer id) {
Vazi, ispravicu

2021-11-04 12:26 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/calls/CrocodilesAPI.java
> +    public static CreateCrocodileResponse getCreatedCrocodile(String accessToken, Integer id) {
U oba slucaja gadjas isti endpoint a nije pravilno da ako radimo get parsujemo response u post klasu. Ako ti je potreban parse u CrocodileResponse-u samo ga napravi tu :)

2021-11-04 12:26 UTC, Aleksandra-Milenkovic commented on src/test/java/com/example/test/api/common/GsonFunctions.java
> +       String json = jsonResponse.toString();
Ups, propustila sam da addujem tu izmenu, to sam isprobavala kombinacije za onaj jsonArray.

2021-11-04 12:26 UTC, Aleksandra-Milenkovic commented on src/test/java/com/example/test/api/constants/DataProviderNames.java
> +    public static final String VERIFY_DELETED_CROCODILE= "" +
Ne znam kako se to desilo, ispravljam.

2021-11-10 09:17 UTC, PetkovicStefan requested changes

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/data/model/crocodiles/PatchCrocodileResponse.java
> +    public void parseResponse(PatchCrocodileNameRequest patchCrocodileRequest, Integer id) {
Eee ovde ja mislim da mi mozemo da postavimo sve propertije :) Pored ovog requesta mozes da prosledis createdCrocodileResponse pa odatle da izvuces propertije koje ne menjas

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/data/provider/crocodile/CrocodileProvider.java
> +                {"CreateCrocodileFirstDataCombination", getAccessToken(), prepareCrocodileRequest()},
Lepo si ovo odradila, samo kao sto ti vec rekoh ovo bi morali smislenije da se imenuje :) Nikome nije jasno sta je firstDataCombination i ostalo. Mada posto je ovo vezbica samo da vidis kako funkcionisu provideri onda moze i da ostane ovako :)

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/asserts/CrocodileAssert.java
> +        this.softAssert.assertNotNull(actualUpdatedCrocodileResponse.getId(), "ID value is null");
Za update mozemo da proverimo i da li je iD equals. Ovo mi je verovatno promaklo da ti napisem da ga ubacis u parseUpdateCrocodileResponse

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/asserts/CrocodileAssert.java
> +    public void assertPatchedCrocodileName(String accessToken, PatchCrocodileResponse actualPatchedCrocodileResponse, PatchCrocodileResponse expectedPatchedCrocodileResponse) {
Tako ces kod ovih patchAsserta da napravis samo jedan, ne treba nam tri i on ce da proverava da li su sva polja equals

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        logStep("INFO: Crocodile is Created");
Jao nisam obracao paznju na log stepovi :P Ovaj drugi kad oznacavas dal je uspesno ne ide INFO nego se pise PASS

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +
fali log step

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        logStep("INFO:Update Crocodile");
Mogla si i ovde metodu createCrocodileAndTakeId da iskoristis

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        CrocodileAssert crocodileAssert= new CrocodileAssert();
log stepovi

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        Integer id = CrocodilesAPI.createCrocodileAndTakeId(accessToken);
mozes i ovde da dodas logove da znamo sta se radi, da ako nam test pukne u tom delu vidimo sta je problem

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/functional/suites/crocodiles/CrocodilesTest.java
> +        CrocodileAssert crocodileAssert= new CrocodileAssert();
log stepovi

2021-11-10 09:17 UTC, PetkovicStefan commented on src/test/java/com/example/test/api/common/GsonFunctions.java
> +    public static ResponseValidation verifyResponse(Response jsonResponse, Class modeledClass){
Jel ovde ima i nekih izmena koje si ti dodavala ili su samo one promene koje sam ti ja poslao?

2021-11-10 14:13 UTC, PetkovicStefan approved these changes

2021-11-10 14:35 UTC, merged